// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGX0WcR0BVCmIPeUpJWvlFjro2wUj4Qo',
    appId: '1:969076038665:web:4ab08f4efcf3479c1a6cd8',
    messagingSenderId: '969076038665',
    projectId: 'notes-89d50',
    authDomain: 'notes-89d50.firebaseapp.com',
    storageBucket: 'notes-89d50.appspot.com',
    measurementId: 'G-B2T4BM4KHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAr0klNSnJRITdiyD7tYfuspRc9ldXsho',
    appId: '1:473180474301:android:967712c0bc036b7713e0d4',
    messagingSenderId: '473180474301',
    projectId: 'noteapp-a212a',
    storageBucket: 'noteapp-a212a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dcLf6yGXp7i30siEb2ggMORrMeTH5Ew',
    appId: '1:473180474301:ios:67781eb7ceb1a54313e0d4',
    messagingSenderId: '473180474301',
    projectId: 'noteapp-a212a',
    storageBucket: 'noteapp-a212a.appspot.com',
    iosBundleId: 'com.example.appGhiChu',
  );

}